# Code generated by //tools/update_versions. DO NOT EDIT.
# Generated at: 2025-11-12T16:34:46Z

"""Version and checksum data for golangci-lint releases."""

DEFAULT_VERSION = "v2.6.1"

GOLANGCI_VERSIONS = {
    "v2.6.1": {
        "darwin": {
            "amd64": "aee6e16af4dfa60dd3c4e39536edc905f28369fda3c138090db00c8233cfe450",
            "arm64": "402e903029391f1b6383cc63c8d0fcd38e879a4dfe3a0aff258a1817d7a296ec",
        },
        "freebsd": {
            "386": "5b5f8691150a4309afb29faaccf6e074fda873aad32175108ab8849fc7eee643",
            "amd64": "1d827001502ca4d9b5287d33bfeb2677aea6eeea85d3b73dae51842817bb407a",
            "arm64": "c54281dd1180904d70261e5a7a025753d9991f8b6c352b3f5cbd2b564ecddb21",
            "armv6": "cf8ce20453c4033f6ee3719c1d8e1f9695389ecd4634f10f63c16a2cf86132e5",
            "armv7": "8acedbce9cd55c61a8563fce30d8458049eb0484ff3985057e3b13d35adb1f00",
        },
        "illumos": {
            "amd64": "19ddb4672f03d5d87be44643d33b9580c01d6995460900c4752b4f9664fb2121",
        },
        "linux": {
            "386": "79bb6342726ccea96abb99a77bece01961f4bece7e44601855f30e01d3efba27",
            "amd64": "c22e188e46aff9b140588abe6828ba271b600ae82b2d6a4f452196a639c17ec0",
            "arm64": "1c22b899f2dd84f9638e0e0352a319a2867b0bb082c5323ad50d8713b65bb793",
            "armv6": "b52331fb224cdc987f8f703120d546a98114c400a453c61a2b51a86d0d669dbe",
            "armv7": "e4b2151c569eb481cd9482f6b1bbf70cf129959e75b918aa5f3cb6acb0745ede",
            "loong64": "3b05e57a9986b1167fe0312b69a214f213abd838ce819fc5d214f7bf957a9934",
            "mips64": "8320b8e74e9a27eba06a2097d46cec4cb27d24bab42d76b718dff56ec1ae53c7",
            "mips64le": "b477314ab5563d522530d49084e2c0ae3b51d75a905d2dd119bb0b70db1e525b",
            "ppc64le": "4f602b3ceeb80975caf78b8b7aebdf9dbc2504ee4c9d74684d56ab467dbc1f70",
            "riscv64": "01ef6a906e66ee883b44da77d316c82b5f5eefb32b8a3ec0d65846ac7e712ae1",
            "s390x": "e8294b712c5d5fd81d35c2eea4885d61476bbffe60a995b2077765b001e49f0c",
        },
        "netbsd": {
            "386": "62d8ff79b4b983c62db94a073b521048779098c074c345402edf9ceaf8adda99",
            "amd64": "7216743807ae34b7588d87706e8e7db2893e143826dfbac2c956ee5001831a4b",
            "arm64": "248c4d0602e3e07fec061b468f1f1c77ae7ce5d2f7fb04902c998b505fc177a1",
            "armv6": "bcf358f8ff28bb4a69c8399be451203b904b6572a2e2b00f1091da48990262f0",
            "armv7": "d0f888c6fa1f9b6f64153f03abc17a73f436c5d678501de1c9daeda61272f423",
        },
        "windows": {
            "386": "d47312b0bd87fa4d0b161001bcebaaaf59203d13444e624b00d2dd240b168dc8",
            "amd64": "b6edeea3d1d52331e98dc6378f710cfe2d752ca1ba09032fe60e62a87a27a25f",
            "arm64": "eff5849a62c2b0076ab55a4b40379c8636028bccfdb8af3cc54af155e18f25dd",
        },
    },
}

def get_golangci_version_info(version = None):
    """Returns (version, checksums_map) for the requested version.

    Args:
        version: Version tag (e.g., "v2.6.1"). If None, uses DEFAULT_VERSION.

    Returns:
        Tuple of (version_string, checksums_dict) where checksums_dict is
        a nested dict: {os: {arch: sha256}}

    Fails:
        If the requested version is not available.
    """
    v = version if version else DEFAULT_VERSION
    if v not in GOLANGCI_VERSIONS:
        fail("Unknown golangci-lint version: {}. Available: {}".format(
            v, ", ".join(GOLANGCI_VERSIONS.keys())
        ))
    return v, GOLANGCI_VERSIONS[v]
